title: DaffaDev
email: your@email.com
description: >-
  Situs sederhana yang memadukan tampilan personal dan blog Jekyll.
baseurl: ""
url: "https://daffadevhosting.github.io"
lang: "id-ID"
author: "DaffaDev"

license_key: "<%= ENV['license_key'] %>"
ads_image: "https://files.sitestatic.net/promotion_banners/202607011814070000009a730a087d__INTER33__1600x2668.jpg"
ads_link: "https://mam.inter33lap.com/register?ref=SGGABAG0982"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - dotenv
  - jekyll-pwa-plugin

pwa:
  sw_src_filepath: sw.js

plugins_dir: _plugins

collections:
  blogpost:
    output: true

permalink: /blogpost/:title/

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
      writer: "Daffa"

markdown: kramdown

exclude:
  - Gemfile.lock
  - node_modules/
  - vendor/
