title: DaffaDev
email: your@email.com
description: >-
  Situs sederhana yang memadukan tampilan personal dan blog Jekyll.
baseurl: ""
url: "https://daffadevhosting.github.io"
lang: "id-ID"
author: "DaffaDev"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  blogpost:
    output: true

permalink: /blog/:title/

compress_html:
  clippings: all
  ignore:
    envs: all

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DaffaDev"
      lang: "id-ID"
  - scope:
      path: ""
      type: "blogpost"
    values:
      layout: "post"
      author: "DaffaDev"
      lang: "id-ID"

markdown: kramdown

exclude:
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - README.md
  - LICENSE
