# Konfigurasi dasar Jekyll
title: "Daffa Blog"
description: "Deskripsi singkat tentang blog Anda."
baseurl: ""  # Jika di root domain, biarkan kosong. Jika di subfolder, misal "/blog"
url: "https://daffadevhosting.github.io"  # Ganti dengan URL situs Anda
logo: /assets/images/jekyll-logo.png

# Informasi penulis (opsional)
author:
  name: "daffa"
  email: "admin@dev.id"

# Layout
permalink: /:title  # Struktur URL postingan

collections:
  product:
    output: true

# Plugins
plugins:
  - jekyll-paginate

# Konfigurasi Paginasi
paginate: 5  # Jumlah post per halaman
paginate_path: "/page:num/"  # Format URL untuk paginasi

# Konfigurasi SASS/SCSS
sass:
  sass_dir: _sass  # Direktori SASS
  style: :compressed  # Bisa diganti ke expanded untuk debugging

# Exclude (file yang tidak di-render oleh Jekyll)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .jekyll-cache
  - .sass-cache
  - _config_dev.yml  # Jika ada konfigurasi khusus untuk development

# Konfigurasi Markdown
markdown: kramdown
kramdown:
  input: GFM  # Gunakan GitHub Flavored Markdown
  auto_ids: true
  toc_levels: 1..3  # Level heading yang muncul di daftar isi

SITE_KEY: 6LenzPkqAAAAAA3EDMs_FOb6kt7JxvbISpo8RzeJ

  # Google Auth
apiKey: AIzaSyA3ra4E7chQhRzERyKW2aFUTRULMb10vxM
authDomain: blogdaffadev.firebaseapp.com
projectId: blogdaffadev
storageBucket: blogdaffadev.firebasestorage.app
databaseURL: https://blogdaffadev-default-rtdb.asia-southeast1.firebasedatabase.app
senderId: 489703180131
appId: 1:489703180131:web:4383f5ef04c1d414ce3556
measurementId: G-ZWW4K4NVQ6
