- nama: Produk 1
  harga: 2000
  image: https://cf.shopee.co.id/file/6549ebebfdff7f4355dc0398f5f5b9e2
  url: /store/produk-1

- nama: Produk 2
  harga: 3000
  image: https://cf.shopee.co.id/file/6549ebebfdff7f4355dc0398f5f5b9e2
  url: /store/produk-2
