- nama: Produk 1
  label: New
  harga: 2000
  image: /images/jekyll-logo.png
  url: /store/produk-1

- nama: Produk 2
  label: 25% off
  harga: 3000
  image: /images/jekyll-logo.png
  url: /store/produk-2
